article/urls.py
# -*- coding: utf-8 -*-
# 'author':'hxy'


from django.urls import path,re_path
from . import views , list_views



app_name='article'
urlpatterns = [
    path('article-column/',views.article_column,name="article_column"),
    path('rename-column/', views.rename_article_column,name="rename_article_column"),
    path('del-column/',views.del_article_column,name="del_article_column"),
    path('article-post/',views.article_post,name="article_post"),
    path('article-list/',views.article_list,name="article_list"),
    re_path('article-detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.article_detail, name="article_detail"),
    path('del-article/', views.del_article, name = "del_article"),
    path('redit-article/<int:article_id>/', views.redit_article, name="redit_article"),
    
    path('list-article-titles/', list_views.article_titles, name="article_titles"),
    path('list-article-titles/<username>/',list_views.article_titles,name="author_articles"),
    #re_path('list-article-detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$', list_views.article_details, name="list_article_detail"), 
    path('article-content/<int:id>/<slug:slug>/', list_views.article_details, name="article_content"),
    path('like_article',views.like_article,name='like_article'),
]

blog/urls.py
# -*- coding: utf-8 -*-
# 'author':'hxy'


from django.urls import path
from blog import views


app_name='blog'
urlpatterns = [
    path('', views.blog_title, name='blog_title'),
    path('<int:article_id>/',views.blog_article,name="blog_detail"),
    path('blogpost/',views.blog_article_post,name="blog_post"),
]

test1/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('blog/',include('blog.urls',namespace='blog',app_name='blog')),
    #path('blog/', include('blog.urls')),
    #path('blog/', include('blog.urls', namespace='blog')),
    #path('blog/', include(('blog.urls', 'blog'), namespace='blog')),
    #re_path(r'^blog/',include('blog.urls'))
    path('account/',include('account.urls', namespace='account')),
    path('pwd-reset/',include("password_reset.urls",namespace='pwd_reset')),
    path('article/', include("article.urls",namespace='article')),
    path('',TemplateView.as_view(template_name="home.html"),name='home'),
    path('favicon.ico',RedirectView.as_view(url='/static/images/favicon.ico'),name='icon'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
from slugify import slugify
from ckeditor_uploader.fields import RichTextUploadingField


class ArticleColumn(models.Model):
    user = models.ForeignKey(User, on_delete= models.CASCADE,related_name="article_column")
    column = models.CharField(max_length=200)
    created = models.DateField(auto_now_add=True)
    
    def __str__(self):
        return self.column

class ArticlePost(models.Model):
    author = models.ForeignKey(User,on_delete=models.CASCADE,related_name="article")
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=500)
    column = models.ForeignKey(ArticleColumn,on_delete=models.CASCADE,related_name="article_column")
    body = RichTextUploadingField(blank=True,null=True,verbose_name="内容")
    user_like=models.ManyToManyField(User,related_name='articles_likes',blank=True)
    user_dislike=models.ManyToManyField(User,related_name='articles_dislikes',blank=True)
    created = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ('-updated',)
        index_together=(('id','slug'),)
    
    def __str__(self):
        return self.title
    
    def save(self,*args,**kargs):
        self.slug = slugify(self.title)
        super(ArticlePost,self).save(*args,**kargs)
    
    def get_absolute_url(self):
        return reverse("article:article_detail",args=[self.id,self.slug])
    
    
    def get_url_path(self):
        return reverse("article:article_content",args=[self.id,self.slug])
        


class  Comment(models.Model):
    article=models.ForeignKey(ArticlePost,on_delete=models.CASCADE,related_name="comments")
    commentor=models.CharField(max_length=50)
    body = RichTextUploadingField(config_name='comment',blank=True,null=True,verbose_name="评论")
    created= models.DateField(auto_now_add=True)
    
    class Meta:
        ordering=('-created',)
    def __str__(self):
        return "Comment by {0} on {1}".format(self.commentor,self.article)
    
# Create your models here.

article/forms.py
# -*- coding: utf-8 -*-
# 'author':'hxy'


from django import forms
from django.contrib.auth.models import User
from .models import ArticleColumn, ArticlePost,Comment

class ArticleColumnForm(forms.ModelForm):
    class Meta:
        model = ArticleColumn
        fields = ("column",)

class ArticlePostForm(forms.ModelForm):
    class Meta:
        model = ArticlePost
        fields = ("title","body")

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)
      

article/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .models import ArticleColumn,ArticlePost
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse,HttpResponseRedirect
from django.urls import reverse
from .forms import ArticleColumnForm,ArticlePostForm
from django.views.decorators.http import require_POST
from django.shortcuts import get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib import messages
import redis
from django.conf import settings

#r=redis.StrictRedis(host=settings.REDIS_HOST,port=settings.REDIS_PORT,db=settings.REDIS_DB)
r = redis.StrictRedis(host="localhost",port=6379,db=0,decode_responses=True)

@login_required(login_url='/account/login/')
@csrf_exempt
def article_column(request):

    if request.method == "GET":
        columns = ArticleColumn.objects.filter(user=request.user)
        column_form=ArticleColumnForm()
        return render(request,"article/column/article_column.html/",{"columns":columns,"column_form":column_form})
    if request.method == "POST":
        column_name = request.POST['column']
        columns = ArticleColumn.objects.filter(user_id=request.user.id,column=column_name)
        if columns:
            return HttpResponse('2')
        else:
            ArticleColumn.objects.create(user=request.user,column=column_name)
            return HttpResponse('1')


@login_required(login_url='/account/login/')
@require_POST
@csrf_exempt
def rename_article_column(request):
    column_name = request.POST['column_name']
    column_id = request.POST['column_id']
    try:
        line = ArticleColumn.objects.get(id=column_id)
        line.column = column_name
        line.save()
        return HttpResponse('1')
    except:
        return HttpResponse('0')

@login_required(login_url='/account/login/')
@require_POST
@csrf_exempt
def del_article_column(request):
    column_id = request.POST['column_id']
    try:
        line = ArticleColumn.objects.get(id=column_id)
        line.delete()
        return HttpResponse('1')
    except:
        return HttpResponse('2')  

@login_required(login_url='/account/login/')
@csrf_exempt
def article_post(request):
    if request.method == "POST":
        article_post_form = ArticlePostForm(data=request.POST)
        columnid=request.POST.get('column_id')
        print(columnid)
        print(article_post_form)
        if article_post_form.is_valid():
            cd = article_post_form.cleaned_data
            try:
                new_article = article_post_form.save(commit=False)
                new_article.author = request.user
                new_article.column = ArticleColumn.objects.get(id=columnid)
                #new_article.column = request.user.article_column.get(id = request.POST['column_id'])
                new_article.save()
                messages.success(request,'发布成功')
                return HttpResponseRedirect(reverse("article:article_list"))
            except:
                messages.error(request,'发布失败')
                return HttpResponseRedirect(reverse("article:article_list"))
        else:
            messages.error(request,'发布失败')
            return HttpResponseRedirect(reverse("article:article_list"))
        
    if request.method == "GET":
        article_post_form = ArticlePostForm()
        article_columns = request.user.article_column.all()
        return render(request, "article/column/article_post.html",{"article_post_form":article_post_form, "article_columns":article_columns})

@login_required(login_url='/account/login/')
def article_list(request):
    article_list = ArticlePost.objects.filter(author=request.user)
    paginator = Paginator(article_list,4)
    page = request.GET.get('page')
    #print(page)
    try:
        current_page = paginator.page(page)
        articles = current_page.object_list
    except PageNotAnInteger:
        current_page = paginator.page(1)
        articles = current_page.object_list
    except EmptyPage:
        current_page = paginator.page(paginator.num_pages)
        articles = current_page.object_list
    return render(request, "article/column/article_list.html",{"articles":articles, "page":current_page})
       
#@login_required(login_url='/account/login/')
def article_detail(request,id,slug):
    article = get_object_or_404(ArticlePost,id=id,slug=slug)
    total_views=r.get("article:{}:views".format(article.id))
    if total_views==None:
        total_views=0

    #total_views=1
    r.zincrby('article_ranking',article.id, 1)
    article_ranking=r.zrange('article_ranking',0,-1,desc=True)[:10] 
    article_ranking_ids = [int(num) for num in article_ranking]
    most_viewed = list(ArticlePost.objects.filter(id__in=article_ranking_ids))
    most_viewed.sort(key=lambda x: article_ranking_ids.index(x.id))
    return render(request,"article/column/article_detail.html",{"article":article,"total_views":total_views,"most_viewed": most_viewed})

@login_required(login_url='/account/login/')
@require_POST
@csrf_exempt
def del_article(request):
    article_id = request.POST['article_id']
    try:
        article = ArticlePost.objects.get(id = article_id)
        article.delete()
        return HttpResponse("1")
    except:
        return HttpResponse("2")


@login_required(login_url='/account/login/')
@csrf_exempt
def redit_article(request, article_id):
    if request.method == "GET":
        article_columns = request.user.article_column.all()
        article = ArticlePost.objects.get(id = article_id)
        this_article_form = ArticlePostForm(initial={"title":article.title,'body':article.body})
        this_article_column = article.column
        return render(request, "article/column/redit_article.html", {"article":article,"article_columns":article_columns, "this_article_column":this_article_column,"this_article_form":this_article_form})
    if request.method == "POST":
        redit_article = ArticlePost.objects.get(id=article_id)
        try:
            redit_article.column = request.user.article_column.get(id=request.POST['column_id'])
            redit_article.title = request.POST['title']
            redit_article.body = request.POST['body']
            redit_article.save()
            messages.success(request,'修改成功')
            return HttpResponseRedirect(reverse("article:article_list"))
        except:
            messages.error(request,'修改失败')
            return HttpResponseRedirect(reverse("article:article_list"))

@login_required(login_url='/account/login/')
@require_POST
@csrf_exempt
def like_article(request):
    article_id=request.POST.get("id")
    action = request.POST.get("action")
    try:
        article=ArticlePost.objects.get(id=article_id)
        if action=='like':
#            if request.user not in article.user_like:
#                if request.user in article.user_dislike:
#                    article.user_dislike.remove(request.user)
#                else:
            article.user_like.add(request.user)
        elif action=='dislike':
#            if request.user  not in article.user_dislike:
#                if request.user in article.user_like:
#                    article.user_like.remove(request.user)
#                else:
            article.user_dislike.add(request.user)
        return HttpResponse("1")
    except:
        return HttpResponse("0")
        
# Create your views here.

templates/article/column/article_column.html
{% extends "article/base.html" %}
{% load staticfiles %}
{% block title %}article column{% endblock %} {% block content %}
<div>
    <p class="text-right"><!--button class="btn btn-primary">add column</button-->
        <button id= "add_column" onclick="add_column()" class="btn btn-primary"> add column</button>
    </p> 
    <table class="table table-hover">
        <tr> 
            <td>序号</td>
            <td>栏目名称</td>
            <td>操作</td> 
        </tr>
        {% for column in columns %} 
        <tr>
            <td>{{ forloop.counter }}</td> 
            <td>{{ column.column }}</td> 
            <td>
                <a name="edit" href="javascript:" onclick="edit_column(this, {{ column.id }})"> 
                    <span class="glyphicon glyphicon-pencil"></span>    
                </a>
                <a name="delete" href="javascript:" onclick="del_column(this, {{ column.id }})">
                    <span class="glyphicon glyphicon-trash" style="margin-left:20px;"></span> 
                </a>    
            </td>
        </tr>
        {% empty %} 
        <p>还没有设置栏目，太懒了。</p> 
        {% endfor %}
    </table> 
</div>

<script type="text/javascript" src='{% static "js/jquery.js" %}'></script> 
<script type="text/javascript" src="{% static 'js/layer.js'%}"></script> 
<script type="text/javascript">
    function add_column() {
        var index = layer.open({
            type: 1,
            skin: "layui-layer-rim",
            area: ["400px", "200px"],
            title: "新增栏目",
            content: '<div class="text-center" style="margin-top:20px">\
                <p> 请输入新的栏目名称</p>\
                    <p>{{ column_form.column }}</p>\
</div > ',
            btn: ['确定', '取消'],
            yes: function (index, layero) {
                column_name = $('#id_column').val();
                $.ajax({
                    url: '{% url "article:article_column" %}',
                    type: 'POST',
                    data: { "column": column_name },
                    success: function (e) {
                        if (e == "1") {
                            parent.location.reload();
                            layer.msg("good");
                        } else {
                            layer.msg("此栏目已有，请更换名称")
                        }
                    },
                });
            },
            btn2: function (index, layero) {
                layer.close(index);
            }
        });
    }

    function edit_column(the, column_id){
        var name = $(the).parents("tr").children("td").eq(1).text(); 
        var index = layer.open({
            type: 1,
            skin: "layui-layer-rim", 
            area: ["400px", "200px"], 
            title: "编辑栏目",
            content: '<div class="text-center" style="margin-top:20px"> <p>请编辑的栏目名称</p><p><input type="text" id="new_name" value="'+name+'"></p> </div>',
            btn:['确定', '取消'],
            yes: function(index, layero){
                new_name = $("#new_name").val();
                $.ajax({
                    url: "{% url 'article:rename_article_column' %}",
                    type: "POST",
                    data: {"column_id": column_id, "column_name": new_name}, 
                    success: function(e){
                        if(e=="1"){ 
                            parent.location.reload(); 
                            layer.msg("good");
                        }else{ 
                            layer.msg("新的名称没有保存,修改失败。")
                        } 
                    },
                }); 
            },
        }); 
    }

    function del_column(the, column_id){
        var name = $(the).parents("tr").children("td").eq(1).text(); 
        layer.open({
            type: 1,
            skin: "layui-layer-rim",
            area: ["400px", "200px"],
            title: "删除栏目",
            content: '<div class="text-center" style="margin-top:20px"><p>是否确定删除{'+name+'}栏目</p> </div>',
            btn:['确定', '取消'], yes: function(){
                $.ajax({
                    url: '{% url "article:del_article_column" %}', 
                    type:"POST",
                    data: {"column_id":column_id},
                    success: function(e){
                        if(e=="1"){ 
                            parent.location.reload(); 
                            layer.msg("has been deleted.");
                        }else{ 
                            layer.msg("删除失败");
                        } 
                    },
                }) 
            },
        }); 
    }
</script>

{% endblock %}

templates/article/column/article_detail.html
{% extends "article/base.html" %}
{% load staticfiles %}
{% block title %}articles list{% endblock %}
{% block content %} 
{% with total_likes=article.user_like.count  total_dislikes=article.user_dislike.count users_like=article.user_like.all users_dislike=article.user_dislike.all %}
<div>
<div class="col-md-9">
    <header>
        <h1>{{ article.title }}</h1> 
        <p>author: <a href="{% url 'article:author_articles' article.author.username %}">{{ article.author.username }}</a>
        <span style="margin-left:20px" class="glyphicon glyphicon-thumbs-up">{{total_likes}}&nbsplike{{total_likes|pluralize}}:&nbsp </span>
        <span style="margin-left:20px" class="glyphicon glyphicon-thumbs-down">
        {{total_dislikes}}&nbspunlike{{total_dislikes|pluralize}}:&nbsp</span>
        <span style="margin-left:20px">{{total_views}}&nbspview{{total_views|pluralize}}</span></p>
        <!--{% for user in users_like %}
         <a href="{% url 'article:author_articles' user %}">{{user}}</a>
         {% endfor %} </span>
         <span style="margin-left:20px" class="glyphicon glyphicon-thumbs-down">{{total_dislikes}}&nbspunlike{{total_dislikes|pluralize}}:&nbsp {% for user in users_dislike %}
         <a href="{% url 'article:author_articles' user %}">{{user}}</a>
         {% endfor %} </span></p>-->
        <p>updated time:{{article.updated}}</p>
        <p>created time:{{article.created}}</p>
        <p>内容:</p>
        <p></p>
    </header>
    
    <link rel="stylesheet" href="{% static 'editor/css/editormd.preview.css' %}" /> 
    <div class="col-md-8"" >{{ article.body|safe}}
    <p class="text-center"> 
       <a onclick="like_article({{article.id}},'like')" href="#">
       <span class="glyphicon glyphicon-thumbs-up">like</span></a> 
       <a onclick="like_article({{article.id}},'dislike')" href="#">
       <span style="margin-left:15px;" class="glyphicon glyphicon-thumbs-down">unlike</span></a> 
    </p> 
    <p class="text-center"><strong>点赞本文的作者</strong></p>
    <p class="text-center">{% for user in users_like %}
         <a href="{% url 'article:author_articles' user %}">{{user}}</a>
         {% empty%}
         还没有人对此文章表态
         {% endfor %} 
    </p>
    </div>
</div>
<div class="col-md-3">
<p class="text-cneter"><h3>最受欢迎的文章</h3></p>
<ol>
{% for art in most_viewed %}
<li>
<a href="{{art.get_url_path}}">{{art.title}}</a></li>
{% endfor %}
</ol>
</div>
</div>
<script src='{% static "js/jquery.js" %}'></script>
<script src="{% static '/ckeditor/ckeditor/ckeditor.js' %}"></script>
<script src="{% static '/ckeditor/ckeditor-init.js' %}"></script> 
<script type="text/javascript" src="{% static 'js/layer.js' %}"></script>
<script type="text/javascript">
function like_article(id,action){
      $.ajax({
              url:"{% url 'article:like_article' %}",
              type:"POST",
              data:{"id":id,"action":action},
              success: function(e){
              if(e=="1"){
                   layer.msg("点赞成功");
                   window.location.reload();
                   }else{
                      layer.msg("点赞失败");
                      window.location.reload();
                   }
                },
});
}
</script>

{% endwith %}
{% endblock %}

templates/article/column/article_list.html
{% extends "article/base.html" %}
{% load staticfiles %}
{% block title %}articles list{% endblock %}
{% block content %} 
<div>
    <table class="table table-hover"> 
        <tr>
            <td>序号</td>
            <td>标题</td> 
            <td>栏目</td>
            <td>操作</td> 
        </tr>
        {% for article in articles %} 
        <tr id={{ article.id }}>
            <td>{{ forloop.counter }}</td>
            <td><a href="{{article.get_absolute_url}}">{{ article.title }}</a></td> 
            <td>{{ article.column }}</td>
            <td>
            <a name="edit" href="{% url 'article:redit_article' article.id %}"<span class="glyphicon glyphicon-pencil"></span></a>
            <a name="delete" href="javascript:" onclick="del_article(this, {{article.id}})">
               <span class="glyphicon glyphicon-trash" style="margin-left:20px;"></span></a>
            </td>
        </tr>
        {% endfor %} 
    </table>
    {% include "paginator.html" %}
</div>

<script type="text/javascript" src='{% static "js/jquery.js" %}'></script> 
<script type="text/javascript" src="{% static 'js/layer.js'%}"></script> 
<script type="text/javascript">
    function del_article(the, article_id){
        var article_name = $(the).parents("tr").children("td").eq(1).text(); 
        layer.open({
            type: 1,
            skin: "layui-layer-rim",
            area: ["400px", "200px"],    
            title: "删除文章",
            content: '<div class="text-center" style="margin-top:20px"><p>是否确定删除《'+article_name+'》</p> </div>',
            btn:['确定', '取消'], yes: function(){
                $.ajax({
                    url: '{% url "article:del_article" %}', 
                    type:"POST",
                    data: {"article_id":article_id}, 
                    success: function(e){
                        if(e=="1"){ 
                            parent.location.reload(); 
                            layer.msg("has been deleted.");
                        }else{ 
                            layer.msg("删除失败");
                        }
                    }, 
                })
            }, 
        });
    } 
</script>



{% endblock %}

templates/article/column/article_post.html
{% extends "article/base.html" %}
{% load staticfiles %}
{% block title %}article column{% endblock %} {% block content %}

<div style="margin-left:10px">
    <form class="form-horizontal" action="." method="post">{% csrf_token %} 
        <div class="row" style="margin-top: 10px;">
            <div class="col-md-2 text-right"><span>标题:</span></div>
            <div class="col-md-10 text-left">{{article_post_form.title}}</div> 
        </div>
        <div class="row" style="margin-top: 10px;">
            <div class="col-md-2 text-right"><span>栏目:</span></div> 
            <div class="col-md-10 text-left">
                <select name="column_id">
                    {% for column in article_columns %}
                    <option value="{{column.id}}">{{column.column}}</option> 
                    {% endfor %}
                </select> 
            </div>
        </div>
        <div class="row" style="margin-top: 10px;">
        </div>
        <div class="row" style="margin-top: 10px;">
            <div class="col-md-2 text-right"><span>内容:</span></div>
            <div class="col-md-10 text-left">{{article_post_form.body}}</div>
            </div> 
        </div>
        <div class="row">
           <input type="submit" class="btn btn-primary btn-lg" value="发布" ">
        </div>
    </form>
</div>

<script src="{% static '/ckeditor/ckeditor/ckeditor.js' %}"></script>
<script src="{% static '/ckeditor/ckeditor-init.js' %}"></script> 


}
</script>
{% endblock %}

templates/article/column/redit_article.html
{% extends "article/base.html" %}
{% load staticfiles %}
{% block title %}article column{% endblock %}
{% block content %}

<div class="container">
<div class="col-md-10">
<div style="margin-left:10px">
    <form class="form-horizontal" action="." method="post">{% csrf_token %} 
        <div class="row" style="margin-top: 10px;">
            <div class="col-md-2 text-right"><span>标题:</span></div>
            <div class="col-md-10 text-left">{{this_article_form.title}}</div> 
        </div>
        <div class="row" style="margin-top: 10px;">
            <div class="col-md-2 text-right"><span>栏目:</span></div> 
            <div class="col-md-10 text-left">
                <select name="column_id">
                    {% for column in article_columns %}
                        {% if column == this_article_column.column %}
                            <option value="{{column.id}}" selected="selected">{{column.column}} </option>
                        {% else %}
                            <option value="{{column.id}}">{{column.column}}</option>
        
                        {% endif %} 
                    {% endfor %}
                </select> 
            </div>
        </div>
        <div class="row" style="margin-top: 10px;">
            <div class="col-md-2 text-right"><span>内容:</span></div> 
            <div  class="col-md-10 text-left">{{this_article_form.body}}</div>
        </div>
        <div class="row">
            <input type="submit" class="btn btn-primary btn-lg" value="发布" ">
        </div>
    </form>
</div>
</div>
</div>
<script src="{% static '/ckeditor/ckeditor/ckeditor.js' %}"></script>
<script src="{% static '/ckeditor/ckeditor-init.js' %}"></script> 
<script type="text/javascript" src='{% static "js/jquery.js" %}'></script>
<script type="text/javascript" src="{% static 'js/layer.js'%}"></script>
{% endblock %}