blog/urls.py
# -*- coding: utf-8 -*-
# 'author':'hxy'


from django.urls import path
from blog import views


app_name='blog'
urlpatterns = [
    path('', views.blog_title, name='blog_title'),
    path('<int:article_id>/',views.blog_article,name="blog_detail"),
    path('blogpost/',views.blog_article_post,name="blog_post"),
]

test1/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('blog/',include('blog.urls',namespace='blog',app_name='blog')),
    #path('blog/', include('blog.urls')),
    #path('blog/', include('blog.urls', namespace='blog')),
    #path('blog/', include(('blog.urls', 'blog'), namespace='blog')),
    #re_path(r'^blog/',include('blog.urls'))
    path('account/',include('account.urls', namespace='account')),
    path('pwd-reset/',include("password_reset.urls",namespace='pwd_reset')),
    path('article/', include("article.urls",namespace='article')),
    path('',TemplateView.as_view(template_name="home.html"),name='home'),
    path('favicon.ico',RedirectView.as_view(url='/static/images/favicon.ico'),name='icon'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
from django.urls import reverse
from slugify import slugify
# Create your models here.
from django.utils import timezone
from django.contrib.auth.models import User

class BlogArticles(models.Model):
    title = models.CharField(max_length=300)
    author = models.ForeignKey(User,on_delete=models.CASCADE, related_name='blog_posts')
    slug = models.SlugField(max_length=500)
    
    body = RichTextUploadingField(blank=True,null=True,verbose_name="内容")
    publish = models.DateTimeField(default=timezone.now)
    
    class Meta:
        ordering = ('-publish',)
        index_together=(('id','slug'),)
    
    def __str__(self):
        return self.title
    
    def save(self,*args,**kargs):
        self.slug = slugify(self.title)
        super(BlogArticles,self).save(*args,**kargs)
    
#    def get_absolute_url(self):
#        return reverse("article:article_detail",args=[self.id,self.slug])
#    
#    
#    def get_url_path(self):
#        return reverse("article:article_content",args=[self.id,self.slug])
        

    

blog/forms.py
# -*- coding: utf-8 -*-
# 'author':'hxy'


from django import forms
from django.contrib.auth.models import User
from .models import BlogArticles


class BlogArticlePostForm(forms.ModelForm):
    class Meta:
        model = BlogArticles
        fields = ("title","body")
    
      

blog/views.py
from django.shortcuts import render,get_object_or_404

# Create your views here.
from .models import BlogArticles
from .forms import BlogArticlePostForm
#from django.views.decorators.http import require_POST
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.urls import reverse


@login_required(login_url='/account/login/')
def blog_title(request):
    blog_list = BlogArticles.objects.filter(author=request.user)
    paginator = Paginator(blog_list,4)
    page = request.GET.get('page')
    #print(page)
    try:
        current_page = paginator.page(page)
        blogs = current_page.object_list
    except PageNotAnInteger:
        current_page = paginator.page(1)
        blogs = current_page.object_list
    except EmptyPage:
        current_page = paginator.page(paginator.num_pages)
        blogs = current_page.object_list
    return render(request,'blog/blog/titles.html',{'blogs':blogs,"page":current_page})



def blog_article(request,article_id):
    #article = BlogArticles.objects.get(id=article_id)
    article =get_object_or_404(BlogArticles,id=article_id)
    pub = article.publish
    return render(request,'blog/blog/content.html',{"article":article,'publish':pub})

@login_required(login_url='/account/login/')
@csrf_exempt
def blog_article_post(request):
    if request.method == "POST":
        blog_article_post_form = BlogArticlePostForm(data=request.POST)
        if blog_article_post_form.is_valid():
            cd = blog_article_post_form.cleaned_data
            try:
                new_blog_article = blog_article_post_form.save(commit=False)
                new_blog_article.author = request.user
                new_blog_article.save()
                messages.success(request,'文章发布成功')
                return HttpResponseRedirect(reverse("blog:blog_title"))
                #return HttpResponse('1')
            except:
                messages.error(request,'对不起，文章发布失败')
                return HttpResponseRedirect(reverse("blog:blog_title"))
                #return HttpResponse('2')
        else:
            messages.error(request,'对不起，文章格式输入错误')
            return HttpResponseRedirect(reverse("blog:blog_title"))
            #return HttpResponse('3')
    if request.method == "GET":
        blog_article_post_form = BlogArticlePostForm()
        return render(request, "blog/blog/blog_post.html",{"blog_article_post_form":blog_article_post_form})

templates/blog/blog/blog_post.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}blog post{% endblock %} {% block content %}

<div style="margin-left:10px">
    <form class="form-horizontal" action="." method="post">{% csrf_token %} 
        <div class="row" style="margin-top: 10px;">
            <div class="col-md-2 text-right"><span>标题:</span></div>
            <div class="col-md-10 text-left">{{blog_article_post_form.title}}</div> 
        </div>
        <div class="row" style="margin-top: 10px;">
        </div>
        <div class="row" style="margin-top: 10px;">
            <div class="col-md-2 text-right"><span>内容:</span></div>
            <div class="col-md-10 text-left">{{blog_article_post_form.body}}</div>
            <div id="editormd" class="col-md-10 text-left">
                <textarea style="display:none;" id="id_body"></textarea>
            </div> 
        </div>
        <div class="row">
            <input type="submit" class="btn btn-primary btn-lg" value="发布" >
        </div>
    </form>
</div>

<script src="{% static '/ckeditor/ckeditor/ckeditor.js' %}"></script>
<script src="{% static '/ckeditor/ckeditor-init.js' %}"></script> 
<!--<script type="text/javascript" src="{% static 'js/json2.js' %}"></script>-->

{% endblock %}

templates/blog/blog/content.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}block article{% endblock %}

{% block content %}
<div class="row text-center vertical-middle-sm">
    <h1>{{ article.title }}</h1>
</div>
<div class="row">
    <div class="col-xs-12 col-md-8">
        <p  class="text-center"><span>{{  article.author.username  }}</span><span
                style="margin-left:20px">{{ publish }}</span></p>
        <div>{{ article.body|safe}}</div>
    </div>
        <div class="col-xs-6 col-md-4">
        <h2>Blog Vhiccup</h2>
        <p>Love is a touch and yet not a touch</p>
        <img width="400px" src="{% static 'images/huoerdun.png' %}" alt="麦田">
        </div>
</div>
{% endblock %}

templates/blog/blog/titles.html
{% extends "base.html" %} 

{% block title %}block titles{% endblock %}
{% load staticfiles %}
{% block content %}
<div class="row text-center vertical-middle-sm">
    <h1>我的博客</h1>
</div>
<div class="row">
    <div class="col-xs-12 col-md-6">
            <table class="table table-hover"> 
        <tr>
            <td>序号</td>
            <td>标题</td> 
            <td>栏目</td>
            <td>操作</td> 
        </tr>
        {% for blog in blogs %} 
        <tr id={{ blog.id }}>
            <td>{{ forloop.counter }}</td>
            <td><a href="{{article.get_absolute_url}}">{{ blog.title }}</a></td> 
            <td>{{blog.publish}}</td>
            <td>
            <a name="edit" href=""<span class="glyphicon glyphicon-pencil"></span></a>
            <a name="delete" href="" onclick="del_article(this, {{article.id}})">
               <span class="glyphicon glyphicon-trash" style="margin-left:20px;"></span></a>
            </td>
        </tr>
        {% endfor %} 
    </table>
    {% include "paginator.html" %}
        <li><srtong><a href="{% url 'blog:blog_post' %}">发布新blog</a></strang></li> 
    </div>
    <div class="col-xs-4 col-md-4">
        <h2>Blog Vhiccup</h2>
        <p>你是我的半截的诗</p>
        <img width="400px" src="{% static 'images/huoerdun.png' %}" alt="麦田">
    </div>
</div>
{% endblock %}