account/urls.py
# -*- coding: utf-8 -*-
# 'author':'hxy'


from django.urls import path
from account import views
from django.conf import settings
from django.contrib.auth import views as auth_views


app_name='account'
urlpatterns = [
    #path('', views.blog_title, name='blog_title'),
    #path('<int:article_id>/',views.blog_article,name="blog_detail"),
    #path('login/',views.user_login, name="user_login"),
    #path('login/',auth_views.LoginView.as_view,name='user_login'),
    path('login/', auth_views.LoginView.as_view(template_name='account/login2.html'), name='user_login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='account/logout.html'),name='user_logout'),
    path('register/',views.register,name="user_register"),
    #path('password-change/',auth_views.PasswordChangeView.as_view(template_name='registration/password_change_form.html'),name='password_change'),
    path('password-change/',auth_views.PasswordChangeView.as_view(template_name='account/password_change_form.html', success_url="/account/password-change-done/"),name='password_change'),
    #path('password-change-done/',auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'),name='password_change_done'),
    path('password-change-done/',auth_views.PasswordChangeDoneView.as_view(template_name='account/password_change_done.html'),name='password_change_done'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name="account/password_reset_form.html", email_template_name="account/password_reset_email.html", success_url='/account/password-reset-done/'), name='password_reset'),
    path('password-reset-done/', auth_views.PasswordResetDoneView.as_view(template_name="account/password_reset_done.html"), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="account/password_reset_confirm.html", success_url='/account/password-reset-complete/'), name="password_reset_confirm"),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='account/password_reset_complete.html'), name='password_reset_complete'),
    path('my-information/',views.myself,name="my_information"),
    path('edit-my-information/',views.myself_edit,name="edit_my_information"),
    path('my-images/',views.my_image,name="my_image"),
]

article/urls.py
# -*- coding: utf-8 -*-
# 'author':'hxy'


from django.urls import path,re_path
from . import views , list_views



app_name='article'
urlpatterns = [
    path('article-column/',views.article_column,name="article_column"),
    path('rename-column/', views.rename_article_column,name="rename_article_column"),
    path('del-column/',views.del_article_column,name="del_article_column"),
    path('article-post/',views.article_post,name="article_post"),
    path('article-list/',views.article_list,name="article_list"),
    re_path('article-detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.article_detail, name="article_detail"),
    path('del-article/', views.del_article, name = "del_article"),
    path('redit-article/<int:article_id>/', views.redit_article, name="redit_article"),
    
    path('list-article-titles/', list_views.article_titles, name="article_titles"),
    path('list-article-titles/<username>/',list_views.article_titles,name="author_articles"),
    #re_path('list-article-detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$', list_views.article_details, name="list_article_detail"), 
    path('article-content/<int:id>/<slug:slug>/', list_views.article_details, name="article_content"),
    path('like_article',views.like_article,name='like_article'),
]

blog/urls.py
# -*- coding: utf-8 -*-
# 'author':'hxy'


from django.urls import path
from blog import views


app_name='blog'
urlpatterns = [
    path('', views.blog_title, name='blog_title'),
    path('<int:article_id>/',views.blog_article,name="blog_detail"),
    path('blogpost/',views.blog_article_post,name="blog_post"),
]

test1/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('blog/',include('blog.urls',namespace='blog',app_name='blog')),
    #path('blog/', include('blog.urls')),
    #path('blog/', include('blog.urls', namespace='blog')),
    #path('blog/', include(('blog.urls', 'blog'), namespace='blog')),
    #re_path(r'^blog/',include('blog.urls'))
    path('account/',include('account.urls', namespace='account')),
    path('pwd-reset/',include("password_reset.urls",namespace='pwd_reset')),
    path('article/', include("article.urls",namespace='article')),
    path('',TemplateView.as_view(template_name="home.html"),name='home'),
    path('favicon.ico',RedirectView.as_view(url='/static/images/favicon.ico'),name='icon'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <!-- <meta http-equiv="X-UA-Compatible" content="IE=Edge"> -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <!--<link rel="shortcut icon" href="{% url 'icon' %}">-->
    <link rel="shortcut icon" href="{% static 'images/favicon.ico'%}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
</head>
<body>
{% include "header.html" %}
  {% if messages %}
  <div class='container'>
    <div class='alert alert-success text-center alert-dismissible'>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
      {% for message in messages %}
        <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p><br/>
      {% endfor %}
    </div>
  </div>
  {% endif %}

    <div class="container">
        {% block content %} 
        {% endblock %}
    </div>
    {% include "footer.html" %}
    {% block javascritp %}{% endblock %}

</body>
</html>

templates/footer.html
<div class="container">
     <hr>
     <p class="text-center">copy right: Vhiccup </p>
     <p class="text-center">contact us with this Email: ihuhiccup@whut.edu.cn </p>
     <p class="text-center">芳踪已去千山外，青梅仍回梦中来。</p>
</div>

templates/header.html
{% load staticfiles %}
 <div class="container">   <nav class="navbar navbar-default" role="navigation"> 
        <div class="navbar-header">
            <a class="navbar-brand" href="http:">
                <img width="200px" src="{% static 'images/newlogo.png' %}">
            </a> 
        </div>
          <div>
          <ul class="nav navbar-nav" role="navigation">
              <li><a href="{% url 'article:article_titles' %}">文章列表</a></li>
              <li><a href="{% url 'home' %}">Home</a></li>
              <li><a href="{% url 'article:article_column' %}">发布博客</a></li>
              <li><a href="{% url 'account:my_information' %}">我的信息</a></li>
              </ul>
              <ul class="nav navbar-nav navbar-right" style="margin-right:10px">
                  {% if user.is_authenticated %}
                  <li><div class="drapdown" style="margin-top:8px">
                           <button class='btn btn-default dropdown-toggle' type='button' id='dropdownMenu' data-toggle='dropdown'>{{ user.username}}<span class='caret'></span></button>
                           <ul class="dropdown-menu">
                               <li><a href="{% url 'account:my_information' %}">个人信息</a></li>
                               <li><a href="{% url 'article:article_column' %}">后台管理</a></li>
                               <li><a href="{% url 'account:password_change' %}">修改密码</a></li>
                           </ul>
                      </div>
                  </li>
                  <li><a href="{% url 'account:user_logout' %}">Logout</a></li>
                  {% else %}
                  <li><a href="{% url 'account:user_login' %}">Login</a></li>
                  <li><a href="{% url 'account:user_register' %}">Sign up</a></li>
                  {% endif %}
                  <!--<li><a href="{% url 'account:user_login' %}">LOGIN</a></li>-->
              </ul>
          </div>
     </nav>
</div>
 
 
 <script src="{% static 'js/jquery.js' %}"></script>
 <script src="{% static 'js/bootstrap.js' %}"></script>       

templates/home.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}Home page{% endblock %}
{% block content %}
<link rel="stylesheet" href="{% static 'mouse/style.css' %}"> 
<div class="text-center">
    <h1>Blog Vhiccup</h1>
    <h3>Dont' be shy, move your mouse around!</h3>
    <h2>动一下你的鼠标试试！</h2>
    {% load staticfiles %}
    <img width="400" src="{% static 'images/huoerdun.png' %}">
</div>
<canvas id='c'></canvas>

<!-- partial -->
<script  src="{% static 'mouse/script.js' %}"></script> 
{% endblock %}

templates/paginator.html
<div class="pagination"> 
    <span class="step-links">
        {% if page.has_previous %}
        <a href="?page={{ page.previous_page_number }}">Previous</a> 
        {% endif %}
        <span class="current">
            Page {{ page.number }} of {{ page.paginator.num_pages }} 
        </span>
        {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">Next</a> {% endif %}
    </span>
</div>
    